version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    container_name: mysqlcontainer
    volumes:
      - ./src/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: patientsdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: dockerapp
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: admin
      DB_PASSWORD: letmein
      DB_NAME: patientsdb
      DB_CONNECTION_LIMIT: 20
      SERVER_PORT: 3000
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge
